### ISSUE TITLE
c9.io

### ISSUE THREAD

**Issue by anonymousxxx02** [dahquan/rattlesnake#40]
can anyone help me make bots run in c9.io ??

**Comment by Nick8fr32** [comment]
I just think u need to have ur workspace public and then put the c9 vps ip thing in the Google chrome console instead of the other ip but I don't know u can try and see if it works

**Comment by anonymousxxx02** [comment]
@Nick8fr32 i alredy try that but nothing hapend

**Comment by kurama129** [comment]
Change it in bot. Js

**Comment by ravyn120** [comment]
i can help with this. I run my bots on a vps and c9.io

**Comment by anonymousxxx02** [comment]
@kurama129 what exactly to change in bot.js
@ravyn120 please tell me what to do

**Comment by ravyn120** [comment]
Well first of all @anonymousxxx02 check in feedme.js that all the ips ex: 127.0.0.1:1337 are changed to YOURC9.IOIP:8081 or 8080. You also have to set your workspace to public so that the web browser can access the inject that the browser is requesting like c9.ioIP.8081/inject. If this doesn't work then i'm not sure.

**Comment by devesh457** [comment]
@anonymousxxx02 in feed me.js change the IP here line 6 and line 48 then change port on line 192 to 8080

**Comment by devesh457** [comment]
And make the VPs public :)
