### ISSUE TITLE
Bot does not reconnect on death...

### ISSUE THREAD

**Issue by mayed505** [dahquan/rattlesnake#89]
the bots wont reconnect of death... i know that since bot counter drops.

**Comment by Lok0n** [comment]
bots works perfect for me

**Comment by WJKH** [comment]
Played upto 2 hours and all bots reconnect.
You should try better proxies.

**Comment by Numan1982** [comment]
:P well i added a feature that makes it reconnect ;)

**Comment by WJKH** [comment]
@Numan1982 if you won't share or PR your enhancement, features, fixes, etc... we don't care what you have done or not because your comments saying you have fixed something without sharing it doesn't help at all and honestly I don't understand the sense of your comments.

**Comment by Numan1982** [comment]
mate who are you? i can comment what i want. so dont try and talk shit mate.
pfft trying to tell me what to comment and not to comment.

**Comment by WJKH** [comment]
I'm WJKH, can't you read?
Put on your glasses, should help.

Who said you can't comment?
I only said no one care about your comments saying you have done something, to be clear you have nothing done here because you didn't contribute to this project or any other.

I'm not your mate, neither a rapper to talk shit.
I only say the the truth or am I wrong and you have contributed to any project here?

Go back to Youtube, you will succeed there with you nice story.
You have done everything, alright. Next :)

**Comment by kurama129** [comment]
nice one wjkh

**Comment by gamer2510** [comment]
Nice👌👌WJHK..

**Comment by gamer2510** [comment]
Nice👌👌WJKH

.

**Comment by mayed505** [comment]
@WJKH i didnt mean bots dont reconnect on same server, what i meant is that when you join a new server the bots will connect to old server + the new server at the same time :/

**Comment by WJKH** [comment]
@mayed505 if you have change server function in your feeder then you need add bot.close there.
I already talk about it in another issue https://github.com/dahquan/rattlesnake/issues/61#issuecomment-223440725

**Comment by mayed505** [comment]
@WJKH where do we place it anywhere?

**Comment by WJKH** [comment]
Before to call spawn function or at the begin of spawn function.

```
bots.forEach(function(bot) {
    bot.close()
})
```

**Comment by mayed505** [comment]
@WJKH but where do we place close() { if(this.conn !== null) { this.conn.close() } }?

**Comment by WJKH** [comment]
@mayed505 you don't need to place close function, you can call it directly.
